# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'forvard.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(120, 100)
        self.rotateRight = QtWidgets.QWidget(Form)
        self.rotateRight.setGeometry(QtCore.QRect(10, 10, 100, 80))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.rotateRight.sizePolicy().hasHeightForWidth())
        self.rotateRight.setSizePolicy(sizePolicy)
        self.rotateRight.setMinimumSize(QtCore.QSize(100, 80))
        self.rotateRight.setStyleSheet("background-color: rgb(255, 112, 112);")
        self.rotateRight.setObjectName("rotateRight")
        self.label = QtWidgets.QLabel(self.rotateRight)
        self.label.setGeometry(QtCore.QRect(20, 10, 61, 61))
        self.label.setStyleSheet("background-image: url(:/Rotations/p.png);")
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("Pictures/p.png"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.labelRight = QtWidgets.QLabel(self.rotateRight)
        self.labelRight.setGeometry(QtCore.QRect(40, 30, 41, 31))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.labelRight.setFont(font)
        self.labelRight.setStyleSheet("background-color: rgba(255, 255, 255, 0);")
        self.labelRight.setAlignment(QtCore.Qt.AlignCenter)
        self.labelRight.setObjectName("labelRight")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.labelRight.setText(_translate("Form", "90"))
