# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'penUp.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(120, 100)
        self.penUp = QtWidgets.QWidget(Form)
        self.penUp.setGeometry(QtCore.QRect(35, 10, 46, 80))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.penUp.sizePolicy().hasHeightForWidth())
        self.penUp.setSizePolicy(sizePolicy)
        self.penUp.setMinimumSize(QtCore.QSize(51, 80))
        self.penUp.setCursor(QtGui.QCursor(QtCore.Qt.OpenHandCursor))
        self.penUp.setStyleSheet("background-color: rgb(142, 255, 116);")
        self.penUp.setObjectName("penUp")
        self.label_6 = QtWidgets.QLabel(self.penUp)
        self.label_6.setGeometry(QtCore.QRect(5, 10, 41, 61))
        self.label_6.setStyleSheet("background-image: url(:/Forvard/v.png);")
        self.label_6.setText("")
        self.label_6.setPixmap(QtGui.QPixmap("Pictures/penUp.png"))
        self.label_6.setScaledContents(True)
        self.label_6.setObjectName("label_6")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))

