# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'forvard.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(120, 100)
        self.rotateLeft = QtWidgets.QWidget(Form)
        self.rotateLeft.setGeometry(QtCore.QRect(10, 10, 100, 80))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.rotateLeft.sizePolicy().hasHeightForWidth())
        self.rotateLeft.setSizePolicy(sizePolicy)
        self.rotateLeft.setMinimumSize(QtCore.QSize(100, 80))
        self.rotateLeft.setCursor(QtGui.QCursor(QtCore.Qt.OpenHandCursor))
        self.rotateLeft.setStyleSheet("background-color: rgb(255, 112, 112);")
        self.rotateLeft.setObjectName("rotateLeft")
        self.label_3 = QtWidgets.QLabel(self.rotateLeft)
        self.label_3.setGeometry(QtCore.QRect(20, 10, 61, 61))
        self.label_3.setStyleSheet("background-image: url(:/Rotations/p.png);")
        self.label_3.setText("")
        self.label_3.setPixmap(QtGui.QPixmap("Pictures/l.png"))
        self.label_3.setScaledContents(True)
        self.label_3.setObjectName("label_3")
        self.labelLeft = QtWidgets.QLabel(self.rotateLeft)
        self.labelLeft.setGeometry(QtCore.QRect(20, 30, 41, 31))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.labelLeft.setFont(font)
        self.labelLeft.setStyleSheet("background-color: rgba(255, 255, 255, 0);")
        self.labelLeft.setAlignment(QtCore.Qt.AlignCenter)
        self.labelLeft.setObjectName("labelLeft")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.labelLeft.setText(_translate("Form", "90"))
